### ISSUE TITLE
Reporter fails for shared_examples from other files

### ISSUE THREAD

**Issue by krzysztof-pawlik-gat** [vbanthia/rspec_html_reporter#6]
Generating a report fails when `shared_examples` are coming from a separate file and context has its own `it`, the reporter fails with:
```
NoMethodError: private method `select' called for nil:NilClass
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:148:in `block in process'
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:144:in `each'
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:144:in `each_with_index'
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:144:in `process'
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:235:in `block in example_group_finished'
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:217:in `open'
  /home/nelchael/.gem/ruby/gems/rspec_html_reporter-1.0.0/lib/rspec_html_reporter.rb:217:in `example_group_finished'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:201:in `block in notify'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `each'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `notify'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:115:in `example_group_finished'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:603:in `run'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
  /home/nelchael/.gem/ruby/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
  /home/nelchael/.gem/ruby/bin/rspec:23:in `load'
  /home/nelchael/.gem/ruby/bin/rspec:23:in `<top (required)>'
```

Steps to reproduce:
1. Create `Gemfile`:
```gemfile
source "https://rubygems.org"
gem "rspec", "~> 3.8.0"
gem "rspec_html_reporter", ">= 1.0.0"
```
2. Create `context.rb`:
```ruby
#!/usr/bin/ruby

RSpec.shared_examples "foo" do |arg|
  it "works" do
    expect("foo-bar-baz").to eq(arg)
  end
end
```
3. Create `spec.rb`:
```ruby
#!/usr/bin/ruby

require_relative "context"

RSpec.describe "an example group" do
  include_examples "foo", "foo-bar-baz"

  it "works again" do
    expect("foo").to eq("foo")
  end
end
```
4. `bundle install`
5. `bundle exec rspec --format d --format RspecHtmlReporter ./spec.rb`

Moving the `shared_examples` block into `spec.rb` seems to fix this, but obviously is not a solution for sharing code between multiple spec files.

**Comment by vbanthia** [comment]
Thank you for reporting this issue. fixed https://github.com/vbanthia/rspec_html_reporter/commit/7d83b67979feb595ff74911f0bb8593aa7a794f9

**Comment by krzysztof-pawlik-gat** [comment]
Thank you! Working as intended.
